Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -34,12 +34,14 @@ jobs:
     - name: Check ETHERSCAN_TOKEN
       run: |
         if [ -z "$ETHERSCAN_TOKEN" ] ; then
-          exit echo "Missing ENV variable ETHERSCAN_TOKEN"
+          echo "Missing ENV variable ETHERSCAN_TOKEN"
+          exit 1
         fi
     - name: Check WEB3_INFURA_PROJECT_ID
       run: |
         if [ -z "$WEB3_INFURA_PROJECT_ID" ] ; then
-          exit echo "Missing ENV variable WEB3_INFURA_PROJECT_ID"
+          echo "Missing ENV variable WEB3_INFURA_PROJECT_ID"
+          exit 1
         fi
 
     - uses: actions/checkout@v1
